services:
  nodejs:
    image: nodejs-nest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-app
    ports:
      - '3000:3000'
    environment:
      - PORT=${PORT}
    depends_on:
    - postgres
    volumes:
      - ./src:/app/src
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
